// Generates the data-derived research docs from the single source of truth in src/game.
// Run: pnpm docs:gen
import { writeFileSync, mkdirSync } from 'node:fs';
import { ALL_CARDS, cardLabel } from '../src/game/cards/deck';
import { CARD_DEFS } from '../src/game/cards/definitions';
import { GENERALS, KINGDOM_INFO } from '../src/game/generals/definitions';
import { SKILLS, SKILLS_BY_ID } from '../src/game/skills/definitions';
import { SOURCES } from '../src/game/content/sources';
import type { CardName } from '../src/game/engine/types';

mkdirSync('docs/research', { recursive: true });
const link = (id: string) => {
  const s = SOURCES[id];
  return `[${s.title}](${s.url}) — *${s.kind}*`;
};
const srcList = (ids: string[]) => [...new Set(ids)].map((id) => `  - ${link(id)}`).join('\n');
const header = (title: string) => `# ${title}\n\n> Generated by \`pnpm docs:gen\` from \`src/game\` — the engine data and this document cannot drift apart.\n> Source kinds: *official* = YOKA / sanguosha.com; *secondary* = wikis, BGG, FAQs, community; *implementation* = open-source engines.\n\n`;

// ── CARDS.md ──
{
  let md = header('Standard Deck — Cards (标准版 游戏牌)');
  md += `Total physical cards: **${ALL_CARDS.length}** = **${ALL_CARDS.filter((c) => !c.ex).length} Standard** + **${ALL_CARDS.filter((c) => c.ex).length} EX**.\n\n`;
  md += 'Verification: the table was reconstructed independently, then cross-checked row-by-row against the BWIKI 标准包卡牌 table as reproduced in wmzy/sanguosha `deck.ts`; both agree on all 108 rows. Unit tests assert 26 Standard cards per suit (every rank twice) and the per-name quantities below.\n\n';
  md += '| Identifier | English | Chinese | Category | Copies | Suit/rank of each copy |\n|---|---|---|---|---|---|\n';
  for (const name of Object.keys(CARD_DEFS) as CardName[]) {
    const d = CARD_DEFS[name];
    const copies = ALL_CARDS.filter((c) => c.name === name);
    md += `| \`${name}\` | ${d.en} | ${d.zh} | ${d.category} / ${d.subtype}${d.range ? ` (range ${d.range})` : ''} | ${copies.length} | ${copies.map((c) => `${cardLabel(c)}${c.ex ? ' EX' : ''}`).join(', ')} |\n`;
  }
  md += '\n## Card effects\n\n';
  for (const name of Object.keys(CARD_DEFS) as CardName[]) {
    const d = CARD_DEFS[name];
    md += `### ${d.en} · ${d.zh} · \`${name}\`\n\n${d.text}\n\n${d.notes ? `*Notes:* ${d.notes}\n\n` : ''}Sources:\n${srcList(d.sources)}\n\n`;
  }
  md += '## Physical card table (id → card)\n\nIds are stable and used by the engine, tests, logs and replays.\n\n| id | card | suit/rank | EX |\n|---|---|---|---|\n';
  for (const c of ALL_CARDS) md += `| ${c.id} | ${CARD_DEFS[c.name].en} | ${cardLabel(c)} | ${c.ex ? 'yes' : ''} |\n`;
  md += '\n## Discrepancies\n\n- **QSanguosha** ([GPL-3.0](https://github.com/Mogara/QSanguosha)) ships a *revised* "standard" package (e.g. Slash ♠5, Peach ♦2, Jink ♦3–♦13 layout) that differs from the 2008 boxed Standard deck. We follow the boxed Standard table (BWIKI / official card list).\n- **EX cards** (Frost Blade ♠2, Renwang Shield ♣2, Lightning ♥Q, Negate ♦Q) were shipped in the Standard box as an "EX" supplement; the host can exclude them in the lobby (104-card deck).\n';
  writeFileSync('docs/research/CARDS.md', md);
}

// ── GENERALS.md ──
{
  let md = header('Standard Generals (标准版 25 武将)');
  md += 'All HP/gender/kingdom values were checked against the official sanguosha.com hero pages 1–25 (quoted verbatim in wmzy/sanguosha research docs, since direct page fetches were blocked by this build environment) and cross-checked with kevinychen/sanguosha data. The Lord gets +1 max HP in games of 5+ players.\n\n';
  md += '| Identifier | English | Chinese | Kingdom | Gender | HP | Lord general | Skills |\n|---|---|---|---|---|---|---|---|\n';
  for (const g of GENERALS) {
    md += `| \`${g.id}\` | ${g.en} | ${g.zh} | ${KINGDOM_INFO[g.kingdom].en} ${KINGDOM_INFO[g.kingdom].zh} | ${g.gender} | ${g.hp} | ${g.isLord ? 'yes' : ''} | ${g.skills.map((s) => `${SKILLS_BY_ID[s].en} ${SKILLS_BY_ID[s].zh}`).join(', ')} |\n`;
  }
  md += '\n## Per-general sources\n\n';
  for (const g of GENERALS) md += `### ${g.en} · ${g.zh} · \`${g.id}\`\n\n*${g.title}*. ${KINGDOM_INFO[g.kingdom].en}, ${g.gender}, ${g.hp} HP.\n\nSources:\n${srcList(g.sources)}\n\n`;
  writeFileSync('docs/research/GENERALS.md', md);
}

// ── SKILLS.md ──
{
  let md = header('Standard Skills (武将技能)');
  md += 'Every skill below is implemented in `src/game/skills/impl.ts` (hooks/actives) or `src/game/engine/legal.ts` (conversions and restrictions) and covered by `src/game/tests/skills.test.ts`.\n\n';
  for (const s of SKILLS) {
    md += `## ${s.en} · ${s.zh} · \`${s.id}\` (${s.gloss})\n\n`;
    md += `- **General:** ${GENERALS.find((g) => g.id === s.general)!.en}\n- **Type:** ${s.type}${s.lord ? ', Lord skill (only active when the owner is the Lord)' : ''}${s.compulsory ? ', compulsory' : ''}\n- **Timing:** ${s.timing}${s.limit ? `\n- **Limit:** ${s.limit}` : ''}\n- **Effect:** ${s.text}\n- **Official text:** ${s.textZh}\n`;
    if (s.notes) md += `- **Notes / rulings:** ${s.notes}\n`;
    md += `- **Sources:**\n${srcList(s.sources)}\n\n`;
  }
  writeFileSync('docs/research/SKILLS.md', md);
}

// ── SOURCES.md ──
{
  let md = '# Sources\n\n> Permanent rule for this project: every researched rule, card, general, skill, expansion or UI behaviour must be recorded here with its original link. The registry lives in `src/game/content/sources.ts`; this file is regenerated by `pnpm docs:gen` and the notes section below is maintained by hand in `scripts/gen-docs.ts`.\n\n';
  md += '| Id | Source | Kind | How it was consulted | Notes |\n|---|---|---|---|---|\n';
  for (const s of Object.values(SOURCES)) {
    md += `| \`${s.id}\` | [${s.title}](${s.url}) | ${s.kind} | ${s.access} | ${s.note ?? ''} |\n`;
  }
  md += `
## Research access notes

- \`cloned\`: the repository was cloned and read directly (wmzy/sanguosha, kevinychen/sanguosha, Mogara/QSanguosha).
- \`search-snippet\`: the page was located through web search and its content was read from search-engine extracts. During this build the environment's network policy **blocked direct fetches** of boardgamegeek.com, wikipedia.org, wiki.biligame.com, sanguosha.com, sanguoshaenglish.blogspot.com, sina.cn and ksyun.com, so full pages could not be opened. Links are kept so they can be re-verified.
- \`cited-by-implementation\`: the official/wiki page is quoted verbatim in a cloned implementation's research notes (wmzy/sanguosha \`docs/research\`), which we read.

## Licensing of reference implementations

- **wmzy/sanguosha** — MIT (LICENSE read). Architecture ideas (React + Vite + Hono + WebSocket) and data cross-checks; no code copied.
- **Mogara/QSanguosha** — GPL-3.0 (LICENSE read). Read only for behaviour comparison; no code copied.
- **kevinychen/sanguosha** — no LICENSE file (all rights reserved by default). Used only to compare established English names; nothing copied.
- No YOKA artwork, logos, portraits, music or sound files are used anywhere.
`;
  writeFileSync('docs/SOURCES.md', md);
}
console.log('docs generated');
